### ISSUE TITLE
Dijkstra source-target bug for L'Échenilleur Calédonien Ex72

### ISSUE THREAD

**Issue by Luke-Poeppel** [Luke-Poeppel/decitala#126]
```
LÉchenilleur_Calédonien_Ex72.xml
Traceback (most recent call last):
  File "/Users/lukepoeppel/moiseaux/tests/test_database.py", line 15, in <module>
    make_database("/Users/lukepoeppel/moiseaux/databases/ODNC.db")
  File "/Users/lukepoeppel/moiseaux/moiseaux/database.py", line 202, in make_database
    res = search.path_finder(
  File "/Users/lukepoeppel/decitala/decitala/search.py", line 199, in path_finder
    best_path = dijkstra.generate_path(
  File "/Users/lukepoeppel/decitala/decitala/path_finding/dijkstra.py", line 90, in generate_path
    source_fragment_id = source["id"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Luke-Poeppel** [comment]
Done in c0c64e325b775c6dcd4c1ebc8e920492af74fd2a.
